# Global settings for GRIDLAND3
# This file allows easy tuning of performance and behavior.

# Network settings for all scanner plugins
network:
  # Timeout in seconds for all HTTP/TCP connection attempts
  timeout: 10
  # Number of retries for failed connections
  retries: 2
  # User-Agent to use for all HTTP requests
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 GRIDLAND3-Scanner"

# Scheduler settings
scheduler:
  # Number of concurrent worker threads for scanning tasks
  max_workers: 50

# External API Integrations
# Store sensitive API keys in environment variables for security.
# Example: export SHODAN_API_KEY="your_key_here"
api_keys:
  shodan: "${SHODAN_API_KEY}"
  virustotal: "${VIRUSTOTAL_API_KEY}"

# Output directories for generated files
output:
  # Directory to save screenshots
  screenshots: "screenshots"
  # Directory to save recorded video clips
  recordings: "recordings"
  # Directory to save Metasploit resource scripts
  metasploit_scripts: "metasploit"
